export default {
  EDIT_ATTACHMENT_RADIUS: 4,
  EDIT_ATTACHMENT_BORDER_COLOR: "#000",
  EDIT_ATTACHMENT_FILL_COLOR: "#fff",
  PORT_ATTACHMENT_BORDER_COLOR: "#348efc",
  PORT_ATTACHMENT_FILL_COLOR: "#fff",
  PORT_ATTACHMENT_SELECTED_COLOR: "#348efc",
  PORT_ATTACHMENT_APPROACHED_COLOR: "rgba(52,142,252,.6)",
  PORT_ATTACHMENT_AWAIT_COLOR: "rgba(52,142,252,.3)",
  SHADOW_COLOR: "rgba(0,0,0,0.2)",
  SHADOW_BLUR: 10,
  SELECTED_SHADOW_COLOR: "rgba(0,0,0,.4)",
};
